### ISSUE TITLE
Consider removing upgradablity tasks in tutorial.

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/starter-kit-gsn#10]
In going through the `Start-kit-gsn` for workshops and with individuals,  I have noticed that the upgradability  portion of the tutorial introduces friction to the learning experience. As the OZ method of  upgrades is an in depth subject itself, perhaps its best if we keep the GSN Starter Kit focused just on the GSN.  The uncommenting process for upgradability lead to a number of a different simple mistakes that nonetheless took significant time to debug.

**Comment by ylv-io** [comment]
Fixed in [c6ae4e2fc1a76f3a68789c3a1f7fdd82ffa2c37e](https://github.com/OpenZeppelin/starter-kit-gsn/commit/c6ae4e2fc1a76f3a68789c3a1f7fdd82ffa2c37e).
