### ISSUE TITLE
Error: A web3 provider is not attached to a window.

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/starter-kit-gsn#14]
When running the GSN Starter Kit in a browser without injected Web3 (e.g. MetaMask) the following error is displayed: `Error: A web3 provider is not attached to a window.`

<img width="470" alt="No web3 provider" src="https://user-images.githubusercontent.com/28278242/66009727-1add1280-e4ff-11e9-8b1a-64ed8c015c76.png">

The starter kit includes no Web3 handling code that isn't used.:
```
  function renderNoWeb3() {
    return (
      <div className={styles.loader}>
        <h3>Web3 Provider Not Found</h3>
        <p>Please, install and run Ganache.</p>
      </div>
    );
  }
```

Need to update the kit with a working no Web3 pattern.

**Comment by ylv-io** [comment]
Hey @abcoathup. Thanks for bringing it up. We've decided to simplify `gsn starter kit` and make it only about GSN. It shouldn't be used at all with metamask. I'll make sure to remove any related code.

**Comment by abcoathup** [comment]
I'll create a new issue in OpenZeppelin Network.js.

**Comment by abcoathup** [comment]
Closing as issue created in OpenZeppelin Network.js
