### ISSUE TITLE
Document how the RelayHub is instantiated locally

### ISSUE THREAD

**Issue by PaulRBerg** [OpenZeppelin/starter-kit-gsn#5]
It's not obvious where and how the RelayHub gets deployed locally. I know that it's always located at `0xD216153c06E857cD7f72665E0aF1d7D82172F494`, but it'd be great to have more details about it.

**Comment by ylv-io** [comment]
Hey @PaulRBerg[
Some details were omitted on purpose to simplify GSN tutorial. RelayHub is deployed during `fund-recipient` command which deploys RelayHub if not present.
[gsn-helpers](https://github.com/OpenZeppelin/openzeppelin-gsn-helpers) is a great way to learn more. The repo has methods for developing and testing GSN related stuff locally. Check it out to learn more.

**Comment by PaulRBerg** [comment]
I forked the repo and added the explanation in README before reading your comment. Sorry! Feel free to ignore the PR.

I personally think it'd be good to talk about the local deployment of RelayHub, because it's a core piece of infrastructure.

**Comment by ylv-io** [comment]
Technically speaking you don't need to deploy it ever explicitly. It is always deployed using `fund-recipient` but if you want you can 😄

**Comment by PaulRBerg** [comment]
Yes, so that silent deployment is what made me do the PR.

Bottom line, I may be pedantic. But the reason I want to understanding the behaviour of the RelayHub locally is that I'll (probably) write tests that will touch it somehow.
